### ISSUE TITLE
Problemstellen werden nicht auf Karte gezeigt

### ISSUE THREAD

**Issue by smooth-baking-powder** [steampixel/RadentscheidWordpressLocations#1]
Hi,

ich habe das Plugin bei uns im Radentscheid eingebunden und habe zum Test direkt einmal eine Problemstelle über "Problemstelle melden" erstellt. Diese wird auch angezeigt, wenn ich im Backend schaue. Leider wird sie aber nicht auf der Karte gezeigt.

Eine Idee, was das eventuell sein könnte?

Problemstelle Seite: https://radentscheid-hamburg.de/mitmachen/problemstellen/#
Problemstelle melden Seite: https://radentscheid-hamburg.de/mitmachen/problemstellen/problemstelle-melden/
Location, wo die Testmarkierung sein soll: 
![2019-10-03 10_44_35-Edit Location ‹ Radentscheid Hamburg — WordPress](https://user-images.githubusercontent.com/21257329/66112496-49c0ba80-e5cb-11e9-917d-3d215868fb16.jpg)

Neu geladen und Cache gelöscht, sowie anderer Browser verwendet:
![2019-10-03 10_44_46-Problemstellen – Radentscheid Hamburg](https://user-images.githubusercontent.com/21257329/66112523-56451300-e5cb-11e9-98d3-102c01878d63.jpg)

Im Debugger und in der Laufzeitanalyse habe ich zumindest schon mal das Bild gefunden. 
![2019-10-03 11_33_28-Problemstellen – Radentscheid Hamburg](https://user-images.githubusercontent.com/21257329/66115945-2b11f200-e5d2-11e9-9c00-57d44f55f9f8.jpg)

**Comment by steampixel** [comment]
Hey. Ich schaue mir das heute Abend mal an.

**Comment by mega-stoffel** [comment]
bei uns in Stuttgart funktioniert es!
--> https://zweirat-stuttgart.de/projekte/schwachstellen-karte

**Comment by smooth-baking-powder** [comment]
Danke fürs schauen nachher.

Habe es zum Prüfen auch mal auf meine Testseite geschoben. Dort habe ich das gleiche Problem, allerdings noch verbunden mit einem Problem beim Bildupload. Hier dazu der Fatal Error:
`Fatal error: Uncaught Error: Call to undefined function Sp\exif_imagetype() in /var/www/html/wp-content/plugins/sp-locations/classes/Thumbnail.php:30 Stack trace: #0 /var/www/html/wp-content/plugins/sp-locations/classes/Thumbnail.php(79): Sp\Thumbnail::getType('/var/www/html/w...') #1 /var/www/html/wp-content/plugins/sp-locations/sp-locations.php(343): Sp\Thumbnail::create('/var/www/html/w...', '/var/www/html/w...', 600) #2 /var/www/html/wp-includes/class-wp-hook.php(286): {closure}(231, Object(WP_Post), true) #3 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #4 /var/www/html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #5 /var/www/html/wp-includes/post.php(3940): do_action('save_post_locat...', 231, Object(WP_Post), true) #6 /var/www/html/wp-includes/post.php(4028): wp_insert_post(Array, false) #7 /var/www/html/wp-admin/includes/post.php(405): wp_update_post(Array) #8 /var/www/html/wp-admin/post.php(218): edit_post() #9 {main} thrown in /var/www/html/wp-content/plugins/sp-locations/classes/Thumbnail.php on line 30`

Vielleicht hilft das ja bei der Fehlerfindung. Wenn du noch was brauchst, gerne melden.

**Comment by steampixel** [comment]
hey @corincorvus Ich habe mal einen neuen Issue zu diesem Thema mit dem exif_imagetype eröffnet: https://github.com/steampixel/RadentscheidWordpressLocations/issues/3

**Comment by steampixel** [comment]
So. Nun zu deinem Problem. Es scheint sich dabei um ein Problem mit einem anderen Plugin oder deinem Theme zu handeln. Schau dir mal dieses Bild an. Es zeigt, dass auch der Marker im Dom auf der Karte geladen wurde. Leider wird die Grafik nicht angezeigt, weil irgendetwas auf deiner Seite das src-Attribut in ein data-src-Attribut umwandelt. Irgendwie schaut das so aus, als wäre da irgendeine Art Lazy-Loader für Bilder am Werk, der da irgendwas vermasselt.
![grafik](https://user-images.githubusercontent.com/2643394/66156088-48ba7800-e621-11e9-890d-ab85e8aa002b.png)
Es ist also irgendein Javascript, was über die Bilder geht und das austauscht. Du kannst das nur testen, indem du einzlne Plugins deaktivierst. Evtl. Gibt es auch in deinem Theme die Option "LazyLoad".

**Comment by steampixel** [comment]
Hey. Ich gehe jetzt erstmal davon aus, dass das Problem behoben ist, nachdem ich keine Rückmeldung bekommen habe. Wenn du noch Hilfe brauchst einfach nochmal melden.
