### ISSUE TITLE
openstreetmap

### ISSUE THREAD

**Issue by chrivosie** [steampixel/RadentscheidWordpressLocations#12]
Hey, wir haben bei uns im Team jemanden der bei OpenStreetMap Berlin mitwirkt, der hat uns darauf hingewiesen, dass zwar Leaflet angegeben ist aber eben nicht osm. Bitte korrigieren.
Wir haben es jetzt erstmal so.
https://www.fahrradfreundliches-falkensee.de/schwachstellen-karte

Grüße

**Comment by steampixel** [comment]
Super! Danke für die Info! Erledige ich bei Gelegenheit.
Viele Grüße

**Comment by steampixel** [comment]
Fertig
