### ISSUE TITLE
Email bei Neueintrag

### ISSUE THREAD

**Issue by chrivosie** [steampixel/RadentscheidWordpressLocations#17]
Gibt es die Möglichkeit eine Email zu generieren, damit der Admin sofort Bescheid bekommt sobald eine neue Schwachstelle gemeldet wurde?
Gruß

**Comment by steampixel** [comment]
Jup. Wäre auch relativ simple zu implementieren. Ich behalte das im Auge und kann mich in 2-3 Wochen darum kümmern. Oder irgendwer wagt einen Pull-Request :-) Na?

**Comment by chrivosie** [comment]
Erstmal vielen Dank für deine immer freundliche und unfassbar schnelle Reaktion. ;)

Wenn ich Ahnung von der Materie hätte, würde ich dir gern helfen. Leider lässt mein Know-how zu wünschen übrig.

**Comment by steampixel** [comment]
Kein Problem ;-)

**Comment by steampixel** [comment]
Die Version 1.8.0 kann nun Mails versenden und dich informieren, wenn es neue Locations gibt. Trage die Mailadresse dazu inden Pluginoptionen ein: Einstellungen -> Location Options
