### ISSUE TITLE
"zurück zur Karte" hinzufügen

### ISSUE THREAD

**Issue by mega-stoffel** [steampixel/RadentscheidWordpressLocations#18]
auf der Detailansicht würde sich ein Link "Zurück zur gesamten Schwachstellenkarte" und/oder noch ein Link zum Eingabe-Formular gut machen. Wenn man nur eine einzige Location per Direktlink teilt und jemand darauf klickt, weiß er/sie nicht, dass da viel mehr Daten zu diesem Projekt dazugehören.

**Comment by steampixel** [comment]
Hi. OK. Ich schaue mal, wann ich dazu komme.
Viele Grüße

**Comment by steampixel** [comment]
Hi,
ich habe in der Version 1.9 eine entsprechende Funktion hinzugefügt.
Du kannst die beiden Links im Backend auf der Options-Seite pflegen. Wenn diese gepflegt sind, werden sie auf den Detailseiten angezeigt.
VG
