### ISSUE TITLE
Problemstelle ohne Bild

### ISSUE THREAD

**Issue by mega-stoffel** [steampixel/RadentscheidWordpressLocations#2]
wenn Problemstellen ohne Bild veröffentlicht werden, wäre es geschickt, wenn in dem Popup auf den Marker keine riesige weiße Fläche für das fehlende Bild reserviert wird, sondern sofort die "Beschreibung" angezeigt wird.

**Comment by steampixel** [comment]
Hey. Die Bilder werden nun nur angezeigt, wenn auch welche dabei sind.

**Comment by mega-stoffel** [comment]
hm, dann ist bei uns ein anderes Verhalten.
Klar, es wird kein Bild geladen, es gibt ja keines. Aber im Code gibt es einen img-Tag, der auf /thumbs/600/ (ohne Bild) verweist. Un dann wird eben auch fast die ganze Seite mit dem fehlenden Bild reserviert. So zum Beispiel:
--> https://zweirat-stuttgart.de/projekte/schwachstellen-karte/#909

**Comment by steampixel** [comment]
Hey. Ich habe die Änderungen hier ins Repository geschoben. Du müsstest die Plugin-Dateien von hier nun nochmal runterladen und bei dir auf der Website überschreiben, damit die Änderungen sichtbar werden.

**Comment by mega-stoffel** [comment]
Super! Das mit der Anzeige der Problemstelle auf der Karte funktioniert nun.
Aber: jetzt wird im Backend bei der Freigabe der Problemstelle kein Bild mehr angezeigt (da steht jetzt "Kein Bild"), obwohl eines vorhanden ist, in der Liste aller "Locations" wird es noch angezeigt, beim Klick auf "Bearbeiten" eben nicht mehr.
Nach der Freigabe wird das Bild auf der Karte angezeigt.

**Comment by steampixel** [comment]
Hey. Ich kann das Problem gerade bei mir in der Testumgebung und auch auf unserer Radentscheid-Seite nicht bestätigen. Wenn du möchtest, kannst du mir gerne mal Zugangsdaten senden. Lege mir dafür einfach einen Nutzer an mit info@steampixel.de. Ich würde dann mal direkt drauf schauen.

**Comment by steampixel** [comment]
OK. Bitte teste doch nochmal bei Gelegenheit.

**Comment by mega-stoffel** [comment]
jetzt bin ich zufrieden. :-)
Vielen Dank!
