### ISSUE TITLE
Ohne Bild kein Eintrag möglich - Keine Fehlermeldung

### ISSUE THREAD

**Issue by derdennis** [steampixel/RadentscheidWordpressLocations#25]
Hallo Steampixel, bei unserer [Ideen-Melde-Seite](https://radentscheid-essen.de/melden-seite/) ist das folgende Problem aufgefallen:

Wenn man das Bild für eine Location auf optional setzt, kann keine Location mehr eingetragen werden. Beim Klick auf den Button passiert einfach nichts. Der funktionierende Shortcode schaut so aus:

`
[steampixel-marker-form selected-type="problem_bike" available-types="problem_side_walk,problem_bike,bike_stand_wish" require-address="false" require-image="true" name-label="Name der Stelle" name-placeholder="Bsp: Radweg in schlechtem Zustand" file-placeholder="Lade ein Bild der Stelle hoch. Bitte nimm uns etwas Arbeit ab und schwärze ggf. Kennzeichen und Gesichter." submit-value="Stelle melden" require-personal-data="false" lat="51.45" lng="7.02"]`

Dann wird man auch auf ein fehlendes Bild hingewiesen. Fügt man eins hinzu ist alles okay.

Aber wenn man `require-image` auf `false` setzt klappt es nicht mehr. Der Text in der  Bild-Überschrift ändert sich aber von _Bild hochladen (max 128MB)_ auf _Bild hochladen (optional max 128MB)_, also irgendwas passiert schon...

Irgendeine Idee, warum das so ist und wie man es beheben kann?

Vielen Dank, Viele Grüße

Dennis

**Comment by derdennis** [comment]
Hmm, Die Browser-Konsole sagt:

```
[Error] TypeError: undefined is not an object (evaluating 'formInput.files[0].name')
	(anonyme Funktion) (app.js:962:84)
	submit (app.js:976)
	(anonyme Funktion) (app.js:1035)
```

Kannst du damit schon was anfangen?

**Comment by steampixel** [comment]
Hi,
ich habe leider gerade Probleme mit GitHub. Muss mal warten und kann gerade nicht pushen. Ich habe das Problem aber behoben. Für den Augenblick sollte es reichen die Datei wp-content/plugins/sp-locations/assets/js/app.js zu überschreiben. Das neue File gibt es hier: https://pastebin.com/raw/xzRc9yyR

Keine Ahnung. Kann gerade in kein Repo pushen. Abwarten und Tee trinken...

**Comment by steampixel** [comment]
OK. Jetzt hat es doch noch irgendwie funktioniert. Seltsam. Version 1.11.1: https://github.com/steampixel/RadentscheidWordpressLocations/blob/master/dist/sp-locations_1.11.1.zip

**Comment by derdennis** [comment]
Zip heruntergeladen, Plugin geupgedated: Alles läuft wie es soll, auch mit optionalen Bildern. Vielen lieben Dank für den superschnellen Fix!

**Comment by steampixel** [comment]
Und das während GitHub teilweise down war. Jetzt ist es offiziell :-)
