### ISSUE TITLE
Plugin flexibler gestalten

### ISSUE THREAD

**Issue by toertsche** [steampixel/RadentscheidWordpressLocations#5]
Schön ware es, wenn man die angezeigten Texte nicht nur über den Quelltext der Seite anpassen könnte, sondern es hierfür Einstellungen gäbe. 

Ebenso für die Parameter, wobei man das mit ein wenig Erfahrung noch hinbekommt.

**Comment by steampixel** [comment]
Hey. Ja das ist generell eine gute Idee. Ich will allerdings warte wie gut das Plugin angenommen wird, bevor ich selbst größere Änderungen einbaue. Die Shortcodes mit den Parametern waren die schnellste Möglichkeit, um das in Wordpress zum Laufen zu bringen. Ich könnte mir aber vorstellen, dass es in Zukunft unter dem Punkt "Locations" im Backend auch noch den Punkt "Karten" oder "Formulare" gibt. In diesen Sektionen könnten dann verschiedene Formulare oder Karten konfiguriert werden.
