### ISSUE TITLE
maker.svg wird nicht angezeigt

### ISSUE THREAD

**Issue by chrivosie** [steampixel/RadentscheidWordpressLocations#6]
Hallo, leider wird die Maker.svg nicht richtig angezeigt. Es kommt nur ein leerer Rahmen.

**Comment by steampixel** [comment]
Hi,
kannst du mir bitte mal den Link zu deiner Karte schicken?
Viele Grüße

**Comment by chrivosie** [comment]
Hey. Na klaro.
https://www.fahrradfreundliches-falkensee.de/schwachstellen-karte/
Da ist eine Stelle markiert. Aber das Maker nicht da.

**Comment by steampixel** [comment]
Also für mich sieht es gerade wirklich danach aus, als ob das Bild einfach nicht auf dem Server liegt. Auch andere Bilder aus diesem Verzeichnis sind nicht vorhanden. Zum Beipspiel kann ich das hier auch nicht abrufen:
https://www.fahrradfreundliches-falkensee.de/wp-content/plugins/sp-locations/assets/img/ajax-loader.gif
Bist du sicher, dass es auf dem Server an der richtigen Stelle liegt? Evtl. ist beim Hochladen was schief gelaufen? Du solltest mit SSH oder FTP nochmal schauen.

**Comment by steampixel** [comment]
Im Repository ist es aber: https://github.com/steampixel/RadentscheidWordpressLocations/tree/master/assets/img

**Comment by chrivosie** [comment]
Ich habe das Plugin über die Plugin Installation Funktion von Wordpress installiert.
In den Image Ordnern liegt auch was drin.

![Screenshot_2019-12-13-10-46-45-171_com android chrome](https://user-images.githubusercontent.com/58830539/70790770-05edec80-1d96-11ea-8fc6-b9c1689e0f97.jpg)

**Comment by steampixel** [comment]
Ah! Jetzt hab ich den Fehler!
Diesen Weg der Installation habe ich nicht bedacht ^^ Da muss ich mir was einfallen lassen :-(

Es ist eigentlich so gedacht, dass bisher die Installationsanleitung befolgt werden muss.

Du hast scheinbar das Zip auf der Seite von Github runtergeladen, welches das Repository enthält. Dieses hast du im Backend von Wordpress dann hochgeladen. Aber ich hatte das garnicht im Sinn, dass man das ja auch so machen kann. Auf jeden Fall führt dieser Weg dazu, dass der Ordner, in dem das Plugin liegt den falschen Namen trägt.

Bitte mache folgendes: Deaktiviere das Plugin (Ich glaube deinstallieren musst du es nicht)
Ändere dann den Namen des Ordners, in dem das Plugin liegt von "RadentscheidWordpressLocations-master" auf "sp-locations". Ich hoffe das geht im Backend.

Ich lasse mir da was einfallen, damit das auch mit dem Download auf diese Art in Zukunft klappt. Da muss ich mal etwas experimentieren.

**Comment by chrivosie** [comment]
Ja das wird es sein. Der downloadbare Ordner muss sp-locations heißen oder in deiner Struktur muss es immer heißen: z.b.: RadentscheidWordpressLocations-master/sp-locations.php

**Comment by steampixel** [comment]
Ja es ist doof, das Github den Namen des Ordners automatisch generiert. Aber ich möchte das eigentlich nicht vom Namen hier auf GitHub abhängig machen. Ich denke ich werde einfach ein fertiges ZIP separat dazu legen in Zukunft.

**Comment by chrivosie** [comment]
Das kling nach einem Plan. Ich versuche nun an die FTP Daten zukommen und den Pfad zu ändern. Im Backend scheint es nicht möglich zu sein. Vielen Dank für deine ausserordentlich schnelle Hilfe.

**Comment by steampixel** [comment]
Alternativ kannst du das Plugin auch deinstallieren (Es werden keine Daten gelöscht). Dann kannst du das ZIP öffnen und den Ordner darin umbenennen. Das kannst du dann hochlande und aktivieren. das sollte dann auch gehen.

**Comment by steampixel** [comment]
Ich lasse das mal offen, damit ich das auf dem Schirm hab.

**Comment by chrivosie** [comment]
Habe den Ordner umbenannt, gezipt und neu installiert. Das Plugin funktioniert auf anhieb. Sobald ich aber die lat und lng in der Marker map änder kommt folgender Fehler.:

Parse error: syntax error, unexpected ' ' (T_STRING), expecting ']' in /data/web/1/000/103/154/410767/htdocs/fahrradfreundliches-falkensee/wp-content/plugins/RadentscheidWordpressLocations-master/shortcodes/steampixel_marker_map.php on line 12

Alle Änderungen geschehen immer mit deaktiviertem Plugin.

**Comment by chrivosie** [comment]
Das selbe Problem auch bei der original ZIP und auch bei Maker form

**Comment by steampixel** [comment]
Ok. Was genau hast du gemacht? Du hast lediglich den Shortcode eingebunden oder? Oder hast du die Datei steampixel_marker_map.php verändert?

**Comment by steampixel** [comment]
Der Fehler weißt übrigens auch darauf hin, dass der Plugin-Ordner noch nicht umbenannt ist, weil in dem Fehler-Code ist ja noch "RadentscheidWordpressLocations-master" zu lesen ist.

**Comment by chrivosie** [comment]
Daher habe ich geschrieben dass es egal mit welcher ZIP, sprich welchem Pfad nicht geht.
Ja die steampixel_maker_map und foam um den Standort zu ändern.

**Comment by chrivosie** [comment]
Ich habe die sp-locations/shortcodes/steampixel_marker_map.php und die sp-locations/shortcodes/steampixel_marker_form.php  jetzt vorher bearbeitet und dann via .zip installiert. Läuft. ;)

**Comment by steampixel** [comment]
OK. Besser, du bearbeitest keine Plugin-Dateien. Sonst ist ja bei einem Update immer alles wieder futsch. Das was du bearbeitet hast sind lediglich die Default-Einstellungen. Nutze lieber die Optionen der Shortcodes, wie in der Readme beschrieben: [steampixel-marker-form lat="49.78" lat="9.94" zoom="13"]
Dann bleiben deine Änderungen auch bei Updates persistent.

**Comment by chrivosie** [comment]
Ja das macht Sinn. Dann schreib das mal mit in den shortcode, da andere Nutzer diese Einstellung immer ändern werden.

**Comment by steampixel** [comment]
OK. Das Zip liegt nun für die neue Version im Ordner /dist/

**Comment by chrivosie** [comment]
Endlich habe ich es geschnallt, denn spätestens nach dem Update wird es weg sein hattest du geschrieben. ;)

Du müsstest die Punkte lat:"49.78" lng:"9.94" einfach in dein shortcode mit rein schreiben, das wäre für mich als DAU viel einfacher zu verstehen. ;)

[steampixel-marker-form selected-type="problem" require-address="false" show-opening-hours="false" require-image="true" name-label="Name der Problemstelle" name-placeholder="Bsp: Radweg in schlechtem Zustand" file-placeholder="Lade ein Bild der Problemstelle hoch. Bitte nimm uns etwas Arbeit ab und schwärze ggf. Kennzeichen und Gesichter." submit-value="Problemstelle melden" require-personal-data="false" lat="52.56" lng="13.09"]

lat: Start-Latitude des Kartenfeldes zum Beispiel "52.56"
lng: Start-Longitude des Kartenfeldes zum Beispiel "13.09"
zoom: Start-Zoom des Kartenfeldes zum Beispiel "13"

**Comment by steampixel** [comment]
Ja danke für den Tip. Done :-)
